### PR TITLE
Fix Postgres create database command

### PR DESCRIPTION
**Pull request by samuelleb11**
Using a template should not begin with 'WITH'.
I removed it from the command.

### CODE REVIEW

**Comment by tomamplius** [comment]
right. it's an issue

**Comment by timdonovanuk** [comment]
Please merge, this is still incorrect here: https://github.com/LibrePhotos/librephotos-linux

**Comment by derneuere** [comment]
Sure, but it will probably still not work, because the Dockerfiles and this repository currently diverge

**Comment by timdonovanuk** [comment]
Welp, you're not wrong there :) thanks anyway

**Comment by RobMahn** [comment]
This is also incorrect in the instructions at https://docs.librephotos.com/1/manual_debian_install/.

**Pull request merged**
